use_frameworks!

platform :ios, '9.0'

target 'SYProgressHUD_Example' do
  pod 'SYProgressHUD', :path => '../'

  target 'SYProgressHUD_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
